import random

IMAGE_SIZE = [360, 638]
SEQUENCE_LEN = 5
NUM_OUTPUT_NEURONS = (IMAGE_SIZE[0]/10) * (IMAGE_SIZE[1]/10) * 3
BALL_IMG_SIZE = [int(IMAGE_SIZE[0]/14), int(IMAGE_SIZE[0]/14)]
BALL_IMG_SIZES = []
NUM_BALL_SIZES = 10
NUM_TRAIN_IMAGES = 30000
NUM_TRAIN_VIDEOS = int(35000/SEQUENCE_LEN)
for i in range(1,NUM_BALL_SIZES):
	BALL_IMG_SIZES.append([ int(BALL_IMG_SIZE[0] * float(i)/NUM_BALL_SIZES), int(BALL_IMG_SIZE[1] * float(i)/NUM_BALL_SIZES) ])

SKIP_FIRST_N_FRAMES = 100
BALL_RANGE = range(1,8)
FULL_CONFIDENCE = 1
ALLOWANCE_FROM_EDGE = max(BALL_IMG_SIZES[-1]) + 5